// D3MO Supabase bridge — Step 1: authenticated read/insert storage
(function(){
  'use strict';
  var SUPABASE_URL='https://asxgjgcphhtbewlhmbog.supabase.co';
  var SUPABASE_PUBLISHABLE_KEY='sb_publishable_lhHJwomvquf44EQUD6UBvA_37fo1YfR';
  var db=null;
  function loadSupabaseClient(){return new Promise(function(resolve,reject){if(window.supabase&&window.supabase.createClient){resolve();return;}var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=function(){reject(new Error('Could not load Supabase client'));};document.head.appendChild(s);});}
  function toDb(l){return{id:l.id,name:l.name||'',category:l.category||'',address:l.address||'',city:l.city||'',state:l.state||'',phone:l.phone||'',website:l.website||'',contact_name:l.contactName||'',contact_title:l.contactTitle||'',contact_email:l.contactEmail||'',score:Number(l.score)||0,risks:l.risks||[],services:l.services||[],summary:l.summary||'',estimated_value:Number(l.estimatedValue)||0,status:l.status||'Saved',source:l.source||'',notes:l.notes||'',call_log:l.callLog||[],submitted_date:l.submittedDate||null,payout:Number(l.bonusAmount)||0,updated_at:new Date().toISOString()};}
  function fromDb(r){return{id:r.id,name:r.name||'',category:r.category||'',address:r.address||'',city:r.city||'',state:r.state||'',phone:r.phone||'',website:r.website||'',contactName:r.contact_name||'',contactTitle:r.contact_title||'',contactEmail:r.contact_email||'',score:Number(r.score)||0,risks:r.risks||[],services:r.services||[],summary:r.summary||'',estimatedValue:Number(r.estimated_value)||0,status:r.status||'Saved',source:r.source||'',notes:r.notes||'',callLog:r.call_log||[],submittedDate:r.submitted_date||null,bonusAmount:Number(r.payout)||0,submissionRecord:true,dateAdded:r.created_at||new Date().toISOString(),lastUpdated:r.updated_at||new Date().toISOString()};}
  function localSave(){try{localStorage.setItem('d3mo-pig-v4',JSON.stringify(window.leads||[]));}catch(e){}}
  function localLoad(){try{var raw=localStorage.getItem('d3mo-pig-v4');if(raw)window.leads=JSON.parse(raw);}catch(e){window.leads=[];}}
  function refreshUI(){try{if(window.renderDashboard)renderDashboard();}catch(e){}try{if(window.updateTopbarEarnings)updateTopbarEarnings();}catch(e){}try{if(window.populateLoadSelect)populateLoadSelect();}catch(e){}try{if(window.populateOutreachSelect)populateOutreachSelect();}catch(e){}}
  function showLogin(){if(document.getElementById('d3mo-auth-gate'))return;var gate=document.createElement('div');gate.id='d3mo-auth-gate';gate.style.cssText='position:fixed;inset:0;z-index:9999;background:#050709;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Inter,sans-serif;color:#f0f4f8';gate.innerHTML='<div style="width:min(420px,100%);background:#0f1318;border:1px solid #2a3d52;border-radius:10px;padding:22px"><div style="font-family:Rajdhani,sans-serif;font-size:24px;font-weight:700;color:#f0c040;margin-bottom:4px">D3MO Lead Engine</div><div style="font-size:12px;color:#a8b8c8;margin-bottom:18px">Sign in to sync leads with Supabase.</div><input id="d3mo-auth-email" type="email" placeholder="Your email" style="width:100%;background:#151b23;border:1px solid #2a3d52;color:#f0f4f8;padding:10px;border-radius:5px;margin-bottom:10px"><button id="d3mo-auth-send" style="width:100%;border:0;border-radius:5px;background:#d4a017;color:#000;padding:10px;font-weight:700;cursor:pointer">Email me a sign-in link</button><div id="d3mo-auth-msg" style="font-size:12px;color:#a8b8c8;margin-top:10px;line-height:1.5"></div></div>';document.body.appendChild(gate);document.getElementById('d3mo-auth-send').onclick=async function(){var email=document.getElementById('d3mo-auth-email').value.trim();var msg=document.getElementById('d3mo-auth-msg');if(!email){msg.textContent='Enter your email first.';return;}msg.textContent='Sending sign-in link...';var result=await db.auth.signInWithOtp({email:email,options:{emailRedirectTo:location.origin+location.pathname}});msg.textContent=result.error?('Error: '+result.error.message):'Check your email, then open the sign-in link on this device.';};}
  function hideLogin(){var g=document.getElementById('d3mo-auth-gate');if(g)g.remove();}
  async function cloudLoad(){var session=(await db.auth.getSession()).data.session;if(!session){localLoad();showLogin();refreshUI();return false;}hideLogin();var res=await db.from('leads').select('*').order('created_at',{ascending:true});if(res.error){console.warn('Supabase load failed; using local storage:',res.error);localLoad();refreshUI();return false;}window.leads=(res.data||[]).map(fromDb);localSave();refreshUI();return true;}
  async function cloudSave(){localSave();var session=(await db.auth.getSession()).data.session;if(!session){showLogin();return false;}var rows=(window.leads||[]).map(toDb);if(!rows.length)return true;var ids=rows.map(function(r){return r.id;});var existing=await db.from('leads').select('id').in('id',ids);if(existing.error){console.warn('Supabase ID check failed:',existing.error);return false;}var have=new Set((existing.data||[]).map(function(r){return r.id;}));var fresh=rows.filter(function(r){return !have.has(r.id);});if(!fresh.length)return true;var res=await db.from('leads').insert(fresh);if(res.error){console.warn('Supabase save failed; local copy retained:',res.error);return false;}return true;}
  async function start(){try{await loadSupabaseClient();db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});window.d3moSupabase=db;window.saveLeads=cloudSave;window.loadLeads=cloudLoad;db.auth.onAuthStateChange(function(event,session){if(session){hideLogin();setTimeout(cloudLoad,0);}else if(event==='SIGNED_OUT'){showLogin();}});await cloudLoad();}catch(e){console.warn('Supabase bridge unavailable; staying on local storage:',e);localLoad();refreshUI();}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
